FROM node:22-alpine

# Set working directory
WORKDIR /app

COPY . .

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# Install deps
#RUN pnpm install --frozen-lockfile

# No stale node_modules copied:
# RUN rm -rf node_modules && pnpm install --frozen-lockfile

# Default command
ENTRYPOINT [ "pnpm", "migration:run" ]