services:
  database:
    image: postgres:latest
    env_file:
      - .env
      - .envexample
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    networks:
      - backend
  api1:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROJECT_NAME=api
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:3000
    restart: no
    # TODO: Healthcheck, dev mode

networks:
  backend: