/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * backend API
 * The backend API description
 * OpenAPI spec version: 0.0.1
 */
export type GetManagementEventsParams = {
  sinceSince?: number;
  toSince?: number;
  /**
   * Pagination number of results
   */
  take?: number;
  /**
   * Pagination number of skipped results
   */
  skip?: number;
};

export type GetEventSpotsParams = {
  /**
   * Pagination number of results
   */
  take?: number;
  /**
   * Pagination number of skipped results
   */
  skip?: number;
};

export type GetEventsParams = {
  sinceSince?: number;
  toSince?: number;
  /**
   * Pagination number of results
   */
  take?: number;
  /**
   * Pagination number of skipped results
   */
  skip?: number;
};

export type OrganizationMembersParams = {
  /**
   * Pagination number of results
   */
  take?: number;
  /**
   * Pagination number of skipped results
   */
  skip?: number;
};

export type AllOrganizationsParams = {
  /**
   * Pagination number of results
   */
  take?: number;
  /**
   * Pagination number of skipped results
   */
  skip?: number;
};

export type UserOrganizationMembershipsParams = {
  /**
   * Pagination number of results
   */
  take?: number;
  /**
   * Pagination number of skipped results
   */
  skip?: number;
};

export interface UpdateEventSpot {
  /** @minLength 6 */
  name?: string;
  /** @minimum 0 */
  price?: number;
}

export interface DeleteEventSpot {
  /** In case of valid value it replaces assigned users with new spot otherwise unset their spot */
  replaceWithSpotId?: number;
}

export interface CreateEventSpot {
  /** @minLength 6 */
  name: string;
  /** @minimum 0 */
  price: number;
}

export interface EventSpotSimple {
  id: number;
  name: string;
  price: number;
}

export interface UpdateEvent {
  /**
   * Event capacity
   * @minimum 0
   */
  capacity?: number;
  codeOfConductLink?: string;
  /** Generate invoices after {@link registrationDeadline} */
  generateInvoices?: boolean;
  /** @minLength 30 */
  longDescription?: string;
  photoPolicyLink?: string;
  registrationDeadline?: string;
  /** @minLength 30 */
  shortDescription?: string;
  since?: string;
  termsAndConditionsLink?: string;
  /** @minLength 6 */
  title?: string;
  until?: string;
  visible?: boolean;
}

/**
 * Additional registration properties
! Must be valid JSON schema
 */
export type CreateEventRegistrationForm = { [key: string]: unknown };

export interface CreateEvent {
  /**
   * Event capacity
   * @minimum 0
   */
  capacity: number;
  codeOfConductLink: string;
  /** Generate invoices after {@link registrationDeadline} */
  generateInvoices: boolean;
  /** @minLength 30 */
  longDescription: string;
  photoPolicyLink: string;
  registrationDeadline: string;
  /** Additional registration properties
! Must be valid JSON schema */
  registrationForm?: CreateEventRegistrationForm;
  /** @minLength 30 */
  shortDescription: string;
  since: string;
  termsAndConditionsLink: string;
  /** @minLength 6 */
  title: string;
  until: string;
  visible?: boolean;
}

/**
 * Spot, must be one of {@link event} spots
 * @nullable
 */
export type EventApplicationSimpleSpotType = EventSpot | null;

export interface EventApplicationSimple {
  createdAt: string;
  event: EventSimple;
  id: string;
  /**
   * Spot, must be one of {@link event} spots
   * @nullable
   */
  spotType: EventApplicationSimpleSpotType;
  user: User;
}

/**
 * @nullable
 */
export type EventSimplePhoto = Photo | null;

export interface EventSimple {
  createdByUser: User;
  id: number;
  /** @nullable */
  photo: EventSimplePhoto;
  registrationDeadline: string;
  shortDescription: string;
  since: string;
  title: string;
  until: string;
  visible: boolean;
}

export type CreateEventApplicationAdditionalFormData = { [key: string]: unknown };

export interface CreateEventApplication {
  additionalFormData: CreateEventApplicationAdditionalFormData;
  idNumber: string;
  invoiceAddress: CreateAddress;
  spotTypeId: number;
}

/**
 * Additional registration form
Each event can have different "requirements"
 * @nullable
 */
export type EventRegistrationForm = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type EventPhoto = Photo | null;

export interface EventLink {
  event: Event;
  id: number;
  link: string;
  name: string;
}

export type EventApplicationAdditionalData = { [key: string]: unknown };

export interface EventSpot {
  event: Event;
  id: number;
  name: string;
  price: number;
}

export interface Event {
  applications: EventApplication[];
  /** Event capacity */
  capacity: number;
  codeOfConductLink: string;
  createdAt: string;
  createdByUser: User;
  /** If true, generate invoices after {@link registrationDeadline} */
  generateInvoices: boolean;
  id: number;
  links: EventLink[];
  longDescription: string;
  /** @nullable */
  photo: EventPhoto;
  photoPolicyLink: string;
  registrationDeadline: string;
  /**
   * Additional registration form
Each event can have different "requirements"
   * @nullable
   */
  registrationForm: EventRegistrationForm;
  shortDescription: string;
  since: string;
  spotTypes: EventSpot[];
  /** Links */
  termsAndConditionsLink: string;
  title: string;
  until: string;
  visible: boolean;
}

/**
 * Spot, must be one of {@link event} spots
 * @nullable
 */
export type EventApplicationSpotType = EventSpot | null;

export interface EventApplication {
  additionalData: EventApplicationAdditionalData;
  createdAt: string;
  event: Event;
  id: string;
  idNumber: string;
  invoiceAddress: Address;
  personalAddress: Address;
  /**
   * Spot, must be one of {@link event} spots
   * @nullable
   */
  spotType: EventApplicationSpotType;
  user: User;
}

export interface OrganizationMemberWithoutOrganization {
  createdAt: string;
  id: string;
  user: User;
}

export interface Organization {
  country: string;
  createdAt: string;
  id: string;
  /** @nullable */
  manager: OrganizationManager;
  name: string;
}

export interface OrganizationMemberWithoutUser {
  createdAt: string;
  id: string;
  organization: Organization;
}

export interface UpdatePhoto {
  file: Blob;
}

/**
 * User gender
 */
export type UpdateUserGender = (typeof UpdateUserGender)[keyof typeof UpdateUserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface UpdateUser {
  /** First name */
  firstName?: string;
  /** User gender */
  gender?: UpdateUserGender;
  /** Last name */
  lastName?: string;
  /**
   * User password
   * @minLength 6
   */
  password?: string;
  personalAddress?: CreateAddress;
  /**
   * Must not contain special characters
   * @minLength 6
   * @pattern /^[a-zA-Z0-9]+$/
   */
  username?: string;
}

export type UserGender = (typeof UserGender)[keyof typeof UserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface Address {
  city: string;
  country: string;
  /** House number with entrace number */
  houseNumber: string;
  id: number;
  street: string;
  zip: string;
}

export interface Photo {
  createdAt: string;
  filename: string;
  id: string;
}

export interface User {
  createdAt: string;
  email: string;
  firstName: string;
  gender: UserGender;
  id: string;
  lastName: string;
  personalAddress: Address;
  photo: Photo;
  updatedAt: string;
  username: string;
}

/**
 * @nullable
 */
export type OrganizationManager = User | null;

/**
 * User gender
 */
export type CreateUserGender = (typeof CreateUserGender)[keyof typeof CreateUserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface CreateAddress {
  city: string;
  country: string;
  /**
   * House number with entrance support
   * @pattern /^(\d+)(\/\d+)?$/
   */
  houseNumber: string;
  street: string;
  zip: string;
}

export interface CreateUser {
  /** User email */
  email: string;
  /** First name */
  firstName: string;
  /** User gender */
  gender: CreateUserGender;
  /** Last name */
  lastName: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
  personalAddress?: CreateAddress;
  /**
   * Must not contain special characters
   * @minLength 6
   * @pattern /^[a-zA-Z0-9]+$/
   */
  username: string;
}

export interface AccessToken {
  /** User access token */
  accessToken: string;
}

export interface LoginUser {
  /** User email or username */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}
