/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * backend API
 * The backend API description
 * OpenAPI spec version: 0.0.1
 */
export type GetManagementEvents200 = {
  data?: Event[];
  pagination?: PaginationDto;
};

export type GetManagementEventsParams = {
  sinceSince?: number;
  toSince?: number;
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type GetRoleAllPermissions200Item =
  (typeof GetRoleAllPermissions200Item)[keyof typeof GetRoleAllPermissions200Item];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoleAllPermissions200Item = {
  eventcreate: "event.create",
  eventupdate: "event.update",
  eventduplicate: "event.duplicate",
  eventmanageApplications: "event.manageApplications",
  organisationcreate: "organisation.create",
  organisationupdate: "organisation.update",
  organisationaddUser: "organisation.addUser",
  organisationupdateUser: "organisation.updateUser",
  organisationdeleteUser: "organisation.deleteUser",
  rolecreate: "role.create",
  roleupdate: "role.update",
  roledelete: "role.delete",
} as const;

export type GetEvents200 = {
  data?: Event[];
  pagination?: PaginationDto;
};

export type GetEventsParams = {
  sinceSince?: number;
  toSince?: number;
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type GetUserApplications200 = {
  data?: EventApplication[];
  pagination?: PaginationDto;
};

export type GetUserApplicationsParams = {
  sinceSince?: number;
  toSince?: number;
};

export type OrganizationMembers200 = {
  data?: OrganizationMember[];
  pagination?: PaginationDto;
};

export type OrganizationMembersParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type TransferManager201 = { [key: string]: unknown };

export type UpdateOrganization201 = { [key: string]: unknown };

export type CreateOrganization201 = { [key: string]: unknown };

export type GetAllUsers200 = {
  data?: User[];
  pagination?: PaginationDto;
};

export type GetAllUsersParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type CreateRolePermissionsItem = (typeof CreateRolePermissionsItem)[keyof typeof CreateRolePermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRolePermissionsItem = {
  eventcreate: "event.create",
  eventupdate: "event.update",
  eventduplicate: "event.duplicate",
  eventmanageApplications: "event.manageApplications",
  organisationcreate: "organisation.create",
  organisationupdate: "organisation.update",
  organisationaddUser: "organisation.addUser",
  organisationupdateUser: "organisation.updateUser",
  organisationdeleteUser: "organisation.deleteUser",
  rolecreate: "role.create",
  roleupdate: "role.update",
  roledelete: "role.delete",
} as const;

export interface CreateRole {
  name: string;
  permissions?: CreateRolePermissionsItem[];
}

export interface InvoiceUrl {
  url: string;
}

export type InvoiceSimpleCurrency = (typeof InvoiceSimpleCurrency)[keyof typeof InvoiceSimpleCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceSimpleCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface InvoiceSimpleItem {
  amount: number;
  id: number;
  name: string;
  price: number;
}

export interface InvoiceSimple {
  constantSymbol: number;
  createdAt: string;
  currency: InvoiceSimpleCurrency;
  iban: string;
  id: string;
  items: InvoiceSimpleItem[];
  subscriber: PaymentSubject;
  supplier: PaymentSubject;
  swift: string;
  variableSymbol: number;
}

export type UpdateEventSpotCurrency = (typeof UpdateEventSpotCurrency)[keyof typeof UpdateEventSpotCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventSpotCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface UpdateEventSpot {
  currency?: UpdateEventSpotCurrency;
  /** @minLength 6 */
  name?: string;
  /**
   * Price in format `1000` => `10.00`
   * @minimum 0
   */
  price?: number;
}

export type CreateEventSpotCurrency = (typeof CreateEventSpotCurrency)[keyof typeof CreateEventSpotCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventSpotCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface CreateEventSpot {
  currency: CreateEventSpotCurrency;
  /** @minLength 6 */
  name: string;
  /**
   * Price in format `1000` => `10.00`
   * @minimum 0
   */
  price: number;
}

export type EventSpotSimpleCurrency = (typeof EventSpotSimpleCurrency)[keyof typeof EventSpotSimpleCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventSpotSimpleCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface EventSpotSimple {
  currency: EventSpotSimpleCurrency;
  id: number;
  name: string;
  price: number;
}

export interface UpdateEvent {
  /**
   * Event capacity
   * @minimum 0
   */
  capacity?: number;
  codeOfConductLink?: string;
  /** Generate invoices after {@link registrationDeadline} */
  generateInvoices?: boolean;
  /**
   * Short description in JSON format for RichText
   * @minLength 30
   */
  longDescription?: string;
  photoPolicyLink?: string;
  registrationDeadline?: string;
  /**
   * Short description in JSON format for RichText
   * @minLength 30
   */
  shortDescription?: string;
  since?: string;
  termsAndConditionsLink?: string;
  /** @minLength 6 */
  title?: string;
  until?: string;
  visible?: boolean;
}

/**
 * @nullable
 */
export type EventSimplePhoto = Photo | null;

export interface EventSimple {
  /** Event capacity */
  capacity: number;
  codeOfConductLink: string;
  createdByUser: User;
  id: number;
  /** @nullable */
  photo: EventSimplePhoto;
  photoPolicyLink: string;
  registrationDeadline: string;
  /** Short description in JSON format for RichText */
  shortDescription: string;
  since: string;
  /** Links */
  termsAndConditionsLink: string;
  title: string;
  until: string;
  visible: boolean;
}

/**
 * Additional registration properties
! Must be valid JSON schema
 */
export type CreateEventRegistrationForm = { [key: string]: unknown };

export interface CreateEvent {
  /**
   * Event capacity
   * @minimum 0
   */
  capacity: number;
  codeOfConductLink: string;
  /** Generate invoices after {@link registrationDeadline} */
  generateInvoices: boolean;
  /**
   * Short description in JSON format for RichText
   * @minLength 30
   */
  longDescription: string;
  photoPolicyLink: string;
  registrationDeadline: string;
  /** Additional registration properties
! Must be valid JSON schema */
  registrationForm?: CreateEventRegistrationForm;
  /**
   * Short description in JSON format for RichText
   * @minLength 30
   */
  shortDescription: string;
  since: string;
  termsAndConditionsLink: string;
  /** @minLength 6 */
  title: string;
  until: string;
  visible?: boolean;
}

/**
 * Additional registration form
Each event can have different "requirements"
 * @nullable
 */
export type EventDetailRegistrationForm = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type EventDetailPhoto = Photo | null;

export interface EventDetailLink {
  id: number;
  link: string;
  name: string;
}

export interface EventDetail {
  applications: number;
  /** Event capacity */
  capacity: number;
  codeOfConductLink: string;
  createdAt: string;
  createdByUser: User;
  id: number;
  links: EventDetailLink[];
  /** Long description in JSON format for RichText */
  longDescription: string;
  /** @nullable */
  photo: EventDetailPhoto;
  photoPolicyLink: string;
  registrationDeadline: string;
  /**
   * Additional registration form
Each event can have different "requirements"
   * @nullable
   */
  registrationForm: EventDetailRegistrationForm;
  /** Short description in JSON format for RichText */
  shortDescription: string;
  since: string;
  /** Links */
  termsAndConditionsLink: string;
  title: string;
  until: string;
  visible: boolean;
}

export type UpdateEventApplicationInvoiceMethod =
  (typeof UpdateEventApplicationInvoiceMethod)[keyof typeof UpdateEventApplicationInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventApplicationInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export type UpdateEventApplicationAdditionalFormData = { [key: string]: unknown };

export interface UpdateEventApplication {
  additionalFormData?: UpdateEventApplicationAdditionalFormData;
  idNumber?: string;
  invoiceAddress?: CreateAddress;
  invoiceMethod?: UpdateEventApplicationInvoiceMethod;
  /** @nullable */
  spotTypeId?: number | null;
}

/**
 * @nullable
 */
export type EventApplicationSimpleWithApplicationsSpotType = SpotTypeSimple | null;

export interface EventApplicationSimpleWithApplications {
  createdAt: string;
  event: EventSimpleWithApplications;
  id: number;
  /** @nullable */
  spotType: EventApplicationSimpleWithApplicationsSpotType;
  user: User;
}

export type CreateEventApplicationInvoiceMethod =
  (typeof CreateEventApplicationInvoiceMethod)[keyof typeof CreateEventApplicationInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventApplicationInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export type CreateEventApplicationAdditionalFormData = { [key: string]: unknown };

export interface CreateEventApplication {
  additionalFormData: CreateEventApplicationAdditionalFormData;
  additionalInformation: string;
  foodRestrictionAllergies: string;
  healthLimitations: string;
  idNumber: string;
  invoiceAddress: CreateAddress;
  /** @nullable */
  invoicedTo: string | null;
  invoiceMethod: CreateEventApplicationInvoiceMethod;
  organization: CreateEventApplicationOrganization;
  /** @nullable */
  spotTypeId?: number | null;
  /** Date until the ID number is valid */
  validUntil: string;
}

export type CreateEventApplicationCustomOrganizationType =
  (typeof CreateEventApplicationCustomOrganizationType)[keyof typeof CreateEventApplicationCustomOrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventApplicationCustomOrganizationType = {
  custom: "custom",
} as const;

export interface CreateEventApplicationCustomOrganization {
  country: string;
  name: string;
  type: CreateEventApplicationCustomOrganizationType;
}

export type CreateEventApplicationExistingOrganizationType =
  (typeof CreateEventApplicationExistingOrganizationType)[keyof typeof CreateEventApplicationExistingOrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventApplicationExistingOrganizationType = {
  organization: "organization",
} as const;

export interface CreateEventApplicationExistingOrganization {
  /** Organization ID */
  id: string;
  type: CreateEventApplicationExistingOrganizationType;
}

export type CreateEventApplicationOrganization =
  | CreateEventApplicationExistingOrganization
  | CreateEventApplicationCustomOrganization;

/**
 * @nullable
 */
export type EventApplicationDetailedWithApplicationsSpotType = SpotTypeSimple | null;

export type EventApplicationDetailedWithApplicationsAdditionalData = { [key: string]: unknown };

/**
 * @nullable
 */
export type EventSimpleWithApplicationsPhoto = Photo | null;

export interface EventSimpleWithApplications {
  applications: number;
  /** Event capacity */
  capacity: number;
  codeOfConductLink: string;
  createdByUser: User;
  id: number;
  /** @nullable */
  photo: EventSimpleWithApplicationsPhoto;
  photoPolicyLink: string;
  registrationDeadline: string;
  /** Short description in JSON format for RichText */
  shortDescription: string;
  since: string;
  /** Links */
  termsAndConditionsLink: string;
  title: string;
  until: string;
  visible: boolean;
}

export interface EventApplicationDetailedWithApplications {
  additionalData: EventApplicationDetailedWithApplicationsAdditionalData;
  createdAt: string;
  customOrganization: EventCustomOrganization;
  event: EventSimpleWithApplications;
  id: number;
  idNumber: string;
  invoiceAddress: Address;
  organization: Organization;
  /** @nullable */
  spotType: EventApplicationDetailedWithApplicationsSpotType;
  user: User;
}

export type SpotTypeSimpleCurrency = (typeof SpotTypeSimpleCurrency)[keyof typeof SpotTypeSimpleCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpotTypeSimpleCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface SpotTypeSimple {
  currency: SpotTypeSimpleCurrency;
  id: number;
  name: string;
  price: number;
}

/**
 * Additional registration form
Each event can have different "requirements"
 * @nullable
 */
export type EventRegistrationForm = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type EventPhoto = Photo | null;

export interface EventLink {
  event: Event;
  id: number;
  link: string;
  name: string;
}

export interface Event {
  applications: EventApplication[];
  /** Event capacity */
  capacity: number;
  codeOfConductLink: string;
  createdAt: string;
  createdByUser: User;
  /** If true, generate invoices after {@link registrationDeadline} */
  generateInvoices: boolean;
  id: number;
  links: EventLink[];
  /** Long description in JSON format for RichText */
  longDescription: string;
  /** @nullable */
  photo: EventPhoto;
  photoPolicyLink: string;
  registrationDeadline: string;
  /**
   * Additional registration form
Each event can have different "requirements"
   * @nullable
   */
  registrationForm: EventRegistrationForm;
  /** Short description in JSON format for RichText */
  shortDescription: string;
  since: string;
  spotTypes: EventSpot[];
  /** Links */
  termsAndConditionsLink: string;
  title: string;
  until: string;
  visible: boolean;
}

/**
 * Spot, must be one of {@link event} spots
 * @nullable
 */
export type EventApplicationSpotType = EventSpot | null;

export type EventApplicationInvoiceMethod =
  (typeof EventApplicationInvoiceMethod)[keyof typeof EventApplicationInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventApplicationInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export type EventApplicationAdditionalData = { [key: string]: unknown };

export interface EventApplication {
  additionalData: EventApplicationAdditionalData;
  additionalInformation: string;
  createdAt: string;
  customOrganization: EventCustomOrganization;
  event: Event;
  foodRestrictionAllergies: string;
  healthLimitations: string;
  id: number;
  idNumber: string;
  invoice: Invoice;
  invoiceAddress: Address;
  /** @nullable */
  invoicedTo: string | null;
  invoiceMethod: EventApplicationInvoiceMethod;
  organization: Organization;
  personalAddress: Address;
  /**
   * Spot, must be one of {@link event} spots
   * @nullable
   */
  spotType: EventApplicationSpotType;
  user: User;
  validUntil: string;
}

export type InvoiceCurrency = (typeof InvoiceCurrency)[keyof typeof InvoiceCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface PaymentSubject {
  address: Address;
  /** @nullable */
  cin: string | null;
  createdAt: string;
  id: string;
  name: string;
  /** @nullable */
  vatId: string | null;
}

export interface InvoiceItem {
  amount: number;
  id: number;
  invoice: Invoice;
  name: string;
  price: number;
}

export interface Invoice {
  constantSymbol: number;
  createdAt: string;
  currency: InvoiceCurrency;
  iban: string;
  id: string;
  items: InvoiceItem[];
  subscriber: PaymentSubject;
  supplier: PaymentSubject;
  swift: string;
  variableSymbol: number;
}

export interface EventCustomOrganization {
  application: EventApplication;
  country: string;
  createdAt: string;
  id: number;
  name: string;
}

export type EventSpotCurrency = (typeof EventSpotCurrency)[keyof typeof EventSpotCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventSpotCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface EventSpot {
  currency: EventSpotCurrency;
  event: Event;
  id: number;
  name: string;
  price: number;
}

export interface AddOrganizationMembers {
  userIds: string[];
}

export interface OrganizationMember {
  createdAt: string;
  id: string;
  organization: Organization;
  user: User;
}

export interface UpdateOrganization {
  address?: CreateAddress;
  cin?: string;
  name?: string;
  vatin?: string;
}

export type PaginationResponseDtoDataItem = { [key: string]: unknown };

export interface PaginationDto {
  /** Current page number */
  currentPage: number;
  /** Total number of pages */
  maxPages: number;
  /** Number of items per page */
  perPage: number;
}

export interface PaginationResponseDto {
  /** Array of requested data */
  data: PaginationResponseDtoDataItem[];
  /** Pagination metadata */
  pagination: PaginationDto;
}

/**
 * @nullable
 */
export type OrganizationManager = User | null;

export interface UpdatePhoto {
  file: Blob;
}

/**
 * @nullable
 */
export type UpdateUserPersonalAddress = CreateAddress | null;

/**
 * User gender
 */
export type UpdateUserGender = (typeof UpdateUserGender)[keyof typeof UpdateUserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface UpdateUser {
  /** First name */
  firstName?: string;
  /** User gender */
  gender?: UpdateUserGender;
  /** Last name */
  lastName?: string;
  /**
   * User password
   * @minLength 6
   */
  password?: string;
  /** @nullable */
  personalAddress?: UpdateUserPersonalAddress;
  /** User phone number */
  phoneNumber?: string;
  /** User phone number prefix */
  phonePrefix?: string;
  /**
   * Must not contain special characters
   * @minLength 6
   * @pattern /^[a-zA-Z0-9]+$/
   */
  username?: string;
}

export type UserGender = (typeof UserGender)[keyof typeof UserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface User {
  birthDate: string;
  createdAt: string;
  email: string;
  firstName: string;
  gender: UserGender;
  id: string;
  lastName: string;
  nationality: string;
  /** @nullable */
  personalAddress: UserPersonalAddress;
  phoneNumber: string;
  phonePrefix: string;
  photo: Photo;
  role: Role;
  updatedAt: string;
  username: string;
}

export type RolePermissionsItem = (typeof RolePermissionsItem)[keyof typeof RolePermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolePermissionsItem = {
  eventcreate: "event.create",
  eventupdate: "event.update",
  eventduplicate: "event.duplicate",
  eventmanageApplications: "event.manageApplications",
  organisationcreate: "organisation.create",
  organisationupdate: "organisation.update",
  organisationaddUser: "organisation.addUser",
  organisationupdateUser: "organisation.updateUser",
  organisationdeleteUser: "organisation.deleteUser",
  rolecreate: "role.create",
  roleupdate: "role.update",
  roledelete: "role.delete",
} as const;

export interface Role {
  id: number;
  name: string;
  permissions: RolePermissionsItem[];
}

export interface Address {
  city: string;
  country: string;
  /** House number with entrance number */
  houseNumber: string;
  id: number;
  street: string;
  zip: string;
}

export interface Organization {
  address: Address;
  /** @nullable */
  cin: string | null;
  createdAt: string;
  id: string;
  /** @nullable */
  manager: OrganizationManager;
  name: string;
  /** @nullable */
  vatin: string | null;
}

export interface OrganizationMemberWithoutUser {
  createdAt: string;
  id: string;
  organization: Organization;
}

/**
 * @nullable
 */
export type UserPersonalAddress = Address | null;

export interface Photo {
  createdAt: string;
  filename: string;
  id: string;
}

export interface AccessToken {
  /** User access token */
  accessToken: string;
}

export interface LoginUser {
  /** User email or username */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}

/**
 * User gender
 */
export type CreateUserGender = (typeof CreateUserGender)[keyof typeof CreateUserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface CreateAddress {
  city: string;
  country: string;
  /**
   * House number with entrance support
   * @pattern /^(\d+)(\/\d+)?$/
   */
  houseNumber: string;
  street: string;
  zip: string;
}

export interface CreateOrganization {
  address: CreateAddress;
  cin?: string;
  name: string;
  vatin?: string;
}

export interface CreateUser {
  /** User birthdate */
  birthDate: string;
  /** User email */
  email: string;
  /** First name */
  firstName: string;
  /** User gender */
  gender: CreateUserGender;
  /** Last name */
  lastName: string;
  /** User nationality */
  nationality: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
  personalAddress?: CreateAddress;
  /** User phone number */
  phoneNumber: string;
  /** User phone number prefix */
  phonePrefix: string;
  /**
   * Must not contain special characters
   * @minLength 6
   * @pattern /^[a-zA-Z0-9]+$/
   */
  username: string;
}

export interface InitializeType {
  organization: CreateOrganization;
  user: CreateUser;
}
