/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * backend API
 * The backend API description
 * OpenAPI spec version: 0.0.1
 */
export interface CreateAddress {
  city: string;
  country: string;
  street: string;
  /**
   * House number with entrance support
   * @pattern /^(\d+)(\/\d+)?$/
   */
  houseNumber: string;
  zip: string;
}

/**
 * User gender
 */
export type CreateUserGender = (typeof CreateUserGender)[keyof typeof CreateUserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface CreateUser {
  /** User email */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
  /** First name */
  firstName: string;
  /** Last name */
  lastName: string;
  /**
   * Must not contain special characters
   * @minLength 6
   * @pattern /^[a-zA-Z0-9_-]+$/
   */
  username: string;
  /** User birthdate */
  birthDate: string;
  /** User nationality */
  nationality: string;
  /** User phone number prefix */
  phonePrefix: string;
  /** User phone number */
  phoneNumber: string;
  /** User gender */
  gender: CreateUserGender;
  personalAddress?: CreateAddress;
}

export interface CreateOrganization {
  name: string;
  legalName: string;
  cin?: string;
  vatin?: string;
  address: CreateAddress;
}

export interface InitialiseType {
  user: CreateUser;
  organization: CreateOrganization;
}

export interface LoginUser {
  /** User email or username */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}

export interface AccessToken {
  /** User access token */
  accessToken: string;
}

export interface ResetPasswordDto {
  /** User token */
  token: string;
  /** User password */
  password: string;
}

export interface Photo {
  id: string;
  filename: string;
  createdAt: string;
}

export interface Address {
  id: number;
  city: string;
  country: string;
  zip: string;
  street: string;
  /** House number with entrance number */
  houseNumber: string;
}

export type RolePermissionsItem = (typeof RolePermissionsItem)[keyof typeof RolePermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolePermissionsItem = {
  eventcreate: "event.create",
  eventupdate: "event.update",
  eventduplicate: "event.duplicate",
  eventmanageApplications: "event.manageApplications",
  eventreviewSugarCubes: "event.reviewSugarCubes",
  organisationcreate: "organisation.create",
  organisationupdate: "organisation.update",
  organisationaddUser: "organisation.addUser",
  organisationupdateUser: "organisation.updateUser",
  organisationdeleteUser: "organisation.deleteUser",
  rolecreate: "role.create",
  roleupdate: "role.update",
  roledelete: "role.delete",
  userupdateRole: "user.updateRole",
  userdelete: "user.delete",
} as const;

export interface Role {
  id: number;
  name: string;
  permissions: RolePermissionsItem[];
}

export type UserGender = (typeof UserGender)[keyof typeof UserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

/**
 * @nullable
 */
export type UserPhoto = Photo | null;

/**
 * @nullable
 */
export type UserPersonalAddress = Address | null;

/**
 * @nullable
 */
export type UserRole = Role | null;

export interface User {
  id: string;
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  /** @nullable */
  birthDate: string | null;
  nationality: string;
  phonePrefix: string;
  phoneNumber: string;
  gender: UserGender;
  /** @nullable */
  pronouns: string | null;
  /** @nullable */
  photo: UserPhoto;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  personalAddress: UserPersonalAddress;
  /** @nullable */
  role: UserRole;
  isDeleted: boolean;
  isVerified: boolean;
}

/**
 * @nullable
 */
export type UpdateUserPersonalAddress = CreateAddress | null;

/**
 * User gender
 */
export type UpdateUserGender = (typeof UpdateUserGender)[keyof typeof UpdateUserGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserGender = {
  male: "male",
  female: "female",
  "non-binary": "non-binary",
  "prefer-not-to-say": "prefer-not-to-say",
} as const;

export interface UpdateUser {
  /** @nullable */
  personalAddress?: UpdateUserPersonalAddress;
  /** @nullable */
  pronouns?: string | null;
  /**
   * User password
   * @minLength 6
   */
  password?: string;
  /** First name */
  firstName?: string;
  /** Last name */
  lastName?: string;
  /**
   * Must not contain special characters
   * @minLength 6
   * @pattern /^[a-zA-Z0-9_-]+$/
   */
  username?: string;
  /** User gender */
  gender?: UpdateUserGender;
  /** User phone number prefix */
  phonePrefix?: string;
  /** User phone number */
  phoneNumber?: string;
}

export interface UpdatePhoto {
  file: Blob;
}

/**
 * @nullable
 */
export type OrganizationManager = User | null;

export interface Organization {
  id: string;
  name: string;
  legalName: string;
  /** @nullable */
  cin: string | null;
  /** @nullable */
  vatin: string | null;
  address: Address;
  isDeleted: boolean;
  /** @nullable */
  manager: OrganizationManager;
  createdAt: string;
}

export interface OrganizationMemberWithoutUser {
  id: string;
  organization: Organization;
  createdAt: string;
}

export interface PaginationDto {
  /** Current page number */
  currentPage: number;
  /** Number of items per page */
  perPage: number;
  /** Total number of pages */
  maxPages: number;
}

export type PaginationResponseDtoDataItem = { [key: string]: unknown };

export interface PaginationResponseDto {
  /** Array of requested data */
  data: PaginationResponseDtoDataItem[];
  /** Pagination metadata */
  pagination: PaginationDto;
}

export interface UpdateOrganization {
  name?: string;
  legalName?: string;
  cin?: string;
  vatin?: string;
  address?: CreateAddress;
}

export interface OrganizationMember {
  id: string;
  organization: Organization;
  user: User;
  createdAt: string;
}

export interface AddOrganizationMembers {
  userIds: string[];
}

export type EventSpotCurrency = (typeof EventSpotCurrency)[keyof typeof EventSpotCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventSpotCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface EventSpot {
  id: number;
  name: string;
  price: number;
  event: Event;
  currency: EventSpotCurrency;
}

export interface EventCustomOrganization {
  id: number;
  application: EventApplication;
  name: string;
  country: string;
  createdAt: string;
}

/**
 * @nullable
 */
export type EventApplicationCustomOrganization = EventCustomOrganization | null;

/**
 * Spot, must be one of {@link event} spots
 * @nullable
 */
export type EventApplicationSpotType = EventSpot | null;

export type EventApplicationAdditionalData = { [key: string]: unknown };

export type EventApplicationInvoiceMethod =
  (typeof EventApplicationInvoiceMethod)[keyof typeof EventApplicationInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventApplicationInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export interface EventApplication {
  id: number;
  user: User;
  event: Event;
  organization: Organization;
  /** @nullable */
  customOrganization: EventApplicationCustomOrganization;
  /**
   * Spot, must be one of {@link event} spots
   * @nullable
   */
  spotType: EventApplicationSpotType;
  additionalData: EventApplicationAdditionalData;
  personalAddress: Address;
  invoiceMethod: EventApplicationInvoiceMethod;
  /** @nullable */
  invoicedTo: string | null;
  invoiceAddress: Address;
  additionalInformation: string;
  allergies: string;
  foodRestriction: string;
  healthLimitations: string;
  validUntil: string;
  idNumber: string;
  /** @nullable */
  priority: number | null;
  createdAt: string;
}

export interface EventLink {
  id: number;
  name: string;
  link: string;
  event: Event;
}

/**
 * @nullable
 */
export type EventPhoto = Photo | null;

/**
 * Additional registration form
Each event can have different "requirements"
 * @nullable
 */
export type EventRegistrationForm = { [key: string]: unknown } | null;

export interface Event {
  /** Short description in JSON format for RichText */
  shortDescription: string;
  /** Long description in JSON format for RichText */
  longDescription: string;
  id: number;
  title: string;
  since: string;
  until: string;
  createdByUser: User;
  createdAt: string;
  /** @nullable */
  photo: EventPhoto;
  spotTypes: EventSpot[];
  applications: EventApplication[];
  links: EventLink[];
  visible: boolean;
  registrationDeadline: string;
  /** If true, generate invoices after {@link registrationDeadline} */
  generateInvoices: boolean;
  /**
   * Additional registration form
Each event can have different "requirements"
   * @nullable
   */
  registrationForm: EventRegistrationForm;
  /** Event capacity */
  capacity: number;
  /** Links */
  termsAndConditionsLink: string;
  photoPolicyLink: string;
  codeOfConductLink: string;
}

export type SpotTypeSimpleCurrency = (typeof SpotTypeSimpleCurrency)[keyof typeof SpotTypeSimpleCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpotTypeSimpleCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface SpotTypeSimple {
  id: number;
  name: string;
  price: number;
  currency: SpotTypeSimpleCurrency;
}

/**
 * @nullable
 */
export type EventSimpleWithApplicationsPhoto = Photo | null;

export interface EventSimpleWithApplications {
  /** Short description in JSON format for RichText */
  shortDescription: string;
  applications: number;
  id: number;
  /** @nullable */
  photo: EventSimpleWithApplicationsPhoto;
  since: string;
  until: string;
  title: string;
  createdByUser: User;
  registrationDeadline: string;
  visible: boolean;
  /** Links */
  termsAndConditionsLink: string;
  photoPolicyLink: string;
  codeOfConductLink: string;
  /** Event capacity */
  capacity: number;
}

export type EventApplicationDetailedWithApplicationsAdditionalData = { [key: string]: unknown };

/**
 * @nullable
 */
export type EventApplicationDetailedWithApplicationsCustomOrganization = EventCustomOrganization | null;

/**
 * @nullable
 */
export type EventApplicationDetailedWithApplicationsSpotType = SpotTypeSimple | null;

export type EventApplicationDetailedWithApplicationsInvoiceMethod =
  (typeof EventApplicationDetailedWithApplicationsInvoiceMethod)[keyof typeof EventApplicationDetailedWithApplicationsInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventApplicationDetailedWithApplicationsInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export interface EventApplicationDetailedWithApplications {
  additionalData: EventApplicationDetailedWithApplicationsAdditionalData;
  id: number;
  createdAt: string;
  idNumber: string;
  /** @nullable */
  customOrganization: EventApplicationDetailedWithApplicationsCustomOrganization;
  organization: Organization;
  user: User;
  /** @nullable */
  spotType: EventApplicationDetailedWithApplicationsSpotType;
  invoiceAddress: Address;
  invoiceMethod: EventApplicationDetailedWithApplicationsInvoiceMethod;
  validUntil: string;
  allergies: string;
  foodRestriction: string;
  healthLimitations: string;
  additionalInformation: string;
  /** @nullable */
  invoicedTo: string | null;
  /** @nullable */
  priority: number | null;
  event: EventSimpleWithApplications;
}

export type CreateEventApplicationExistingOrganizationType =
  (typeof CreateEventApplicationExistingOrganizationType)[keyof typeof CreateEventApplicationExistingOrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventApplicationExistingOrganizationType = {
  organization: "organization",
} as const;

export interface CreateEventApplicationExistingOrganization {
  type: CreateEventApplicationExistingOrganizationType;
  /** Organization ID */
  id: string;
}

export type CreateEventApplicationCustomOrganizationType =
  (typeof CreateEventApplicationCustomOrganizationType)[keyof typeof CreateEventApplicationCustomOrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventApplicationCustomOrganizationType = {
  custom: "custom",
} as const;

export interface CreateEventApplicationCustomOrganization {
  type: CreateEventApplicationCustomOrganizationType;
  name: string;
  country: string;
}

export type CreateEventApplicationOrganization =
  | CreateEventApplicationExistingOrganization
  | CreateEventApplicationCustomOrganization;

export type CreateEventApplicationAdditionalFormData = { [key: string]: unknown };

export type CreateEventApplicationInvoiceMethod =
  (typeof CreateEventApplicationInvoiceMethod)[keyof typeof CreateEventApplicationInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventApplicationInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export interface CreateEventApplication {
  organization: CreateEventApplicationOrganization;
  /** @nullable */
  spotTypeId?: number | null;
  additionalFormData: CreateEventApplicationAdditionalFormData;
  invoiceMethod: CreateEventApplicationInvoiceMethod;
  /** @nullable */
  invoicedTo: string | null;
  invoiceAddress: CreateAddress;
  additionalInformation: string;
  allergies: string;
  foodRestriction: string;
  healthLimitations: string;
  /** Date until the ID number is valid */
  validUntil: string;
  idNumber: string;
}

/**
 * @nullable
 */
export type EventApplicationSimpleWithApplicationsSpotType = SpotTypeSimple | null;

export interface EventApplicationSimpleWithApplications {
  event: EventSimpleWithApplications;
  createdAt: string;
  id: number;
  user: User;
  /** @nullable */
  priority: number | null;
  /** @nullable */
  spotType: EventApplicationSimpleWithApplicationsSpotType;
}

export type UpdateEventApplicationExistingOrganizationType =
  (typeof UpdateEventApplicationExistingOrganizationType)[keyof typeof UpdateEventApplicationExistingOrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventApplicationExistingOrganizationType = {
  organization: "organization",
} as const;

export interface UpdateEventApplicationExistingOrganization {
  type: UpdateEventApplicationExistingOrganizationType;
  id: string;
}

export type UpdateEventApplicationCustomOrganizationType =
  (typeof UpdateEventApplicationCustomOrganizationType)[keyof typeof UpdateEventApplicationCustomOrganizationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventApplicationCustomOrganizationType = {
  custom: "custom",
} as const;

export interface UpdateEventApplicationCustomOrganization {
  type: UpdateEventApplicationCustomOrganizationType;
  id?: number;
  name: string;
  country: string;
}

export type UpdateEventApplicationOrganization =
  | UpdateEventApplicationExistingOrganization
  | UpdateEventApplicationCustomOrganization;

export type UpdateEventApplicationInvoiceMethod =
  (typeof UpdateEventApplicationInvoiceMethod)[keyof typeof UpdateEventApplicationInvoiceMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventApplicationInvoiceMethod = {
  personal: "personal",
  organisation: "organisation",
  different: "different",
} as const;

export interface UpdateEventApplication {
  organization: UpdateEventApplicationOrganization;
  idNumber?: string;
  /** Date until the ID number is valid */
  validUntil?: string;
  /** @nullable */
  invoicedTo?: string | null;
  invoiceMethod?: UpdateEventApplicationInvoiceMethod;
  allergies?: string;
  foodRestriction?: string;
  healthLimitations?: string;
  additionalInformation?: string;
  invoiceAddress?: CreateAddress;
}

export interface EventApplicationPriorityDto {
  applicationId: number;
  /** @minimum 1 */
  priority: number;
}

export interface UpdateEventApplicationPrioritiesDto {
  priorities: EventApplicationPriorityDto[];
}

export interface UpdateApplicationSlotDto {
  /** @nullable */
  spotId: number | null;
}

export interface EventDetailLink {
  id: number;
  name: string;
  link: string;
}

/**
 * Additional registration form
Each event can have different "requirements"
 * @nullable
 */
export type EventDetailRegistrationForm = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type EventDetailPhoto = Photo | null;

export interface EventDetail {
  /** Short description in JSON format for RichText */
  shortDescription: string;
  /** Long description in JSON format for RichText */
  longDescription: string;
  links: EventDetailLink[];
  applications: number;
  id: number;
  /** Event capacity */
  capacity: number;
  codeOfConductLink: string;
  photoPolicyLink: string;
  /** Links */
  termsAndConditionsLink: string;
  createdAt: string;
  registrationDeadline: string;
  /**
   * Additional registration form
Each event can have different "requirements"
   * @nullable
   */
  registrationForm: EventDetailRegistrationForm;
  since: string;
  until: string;
  title: string;
  visible: boolean;
  createdByUser: User;
  /** @nullable */
  photo: EventDetailPhoto;
}

export interface CreateEventLinkPartial {
  name: string;
  link: string;
}

/**
 * Additional registration properties
! Must be valid JSON schema
 */
export type CreateEventRegistrationForm = { [key: string]: unknown };

export interface CreateEvent {
  /** Short description in JSON format for RichText */
  longDescription: string;
  /** Short description in JSON format for RichText */
  shortDescription: string;
  /** @minLength 6 */
  title: string;
  since: string;
  until: string;
  registrationDeadline: string;
  links?: CreateEventLinkPartial[];
  visible?: boolean;
  /** Additional registration properties
! Must be valid JSON schema */
  registrationForm?: CreateEventRegistrationForm;
  /** Generate invoices after {@link registrationDeadline} */
  generateInvoices: boolean;
  /**
   * Event capacity
   * @minimum 0
   */
  capacity: number;
  termsAndConditionsLink: string;
  photoPolicyLink: string;
  codeOfConductLink: string;
}

/**
 * @nullable
 */
export type EventSimplePhoto = Photo | null;

export interface EventSimple {
  /** Short description in JSON format for RichText */
  shortDescription: string;
  id: number;
  /** @nullable */
  photo: EventSimplePhoto;
  since: string;
  until: string;
  title: string;
  createdByUser: User;
  registrationDeadline: string;
  visible: boolean;
  /** Links */
  termsAndConditionsLink: string;
  photoPolicyLink: string;
  codeOfConductLink: string;
  /** Event capacity */
  capacity: number;
}

export interface UpdateEventLinkPartial {
  name: string;
  link: string;
  /** @nullable */
  id: number | null;
}

export interface UpdateEvent {
  /** Short description in JSON format for RichText */
  longDescription?: string;
  /** Short description in JSON format for RichText */
  shortDescription?: string;
  links: UpdateEventLinkPartial[];
  /** @minLength 6 */
  title?: string;
  since?: string;
  until?: string;
  registrationDeadline?: string;
  visible?: boolean;
  /** Generate invoices after {@link registrationDeadline} */
  generateInvoices?: boolean;
  /**
   * Event capacity
   * @minimum 0
   */
  capacity?: number;
  termsAndConditionsLink?: string;
  photoPolicyLink?: string;
  codeOfConductLink?: string;
}

export type EventSpotSimpleCurrency = (typeof EventSpotSimpleCurrency)[keyof typeof EventSpotSimpleCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventSpotSimpleCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface EventSpotSimple {
  id: number;
  name: string;
  price: number;
  currency: EventSpotSimpleCurrency;
}

export type CreateEventSpotCurrency = (typeof CreateEventSpotCurrency)[keyof typeof CreateEventSpotCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventSpotCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface CreateEventSpot {
  /** @minLength 6 */
  name: string;
  /**
   * Price in format `1000`
   * @minimum 0
   */
  price: number;
  currency: CreateEventSpotCurrency;
}

export type UpdateEventSpotCurrency = (typeof UpdateEventSpotCurrency)[keyof typeof UpdateEventSpotCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventSpotCurrency = {
  CZK: "CZK",
  EUR: "EUR",
} as const;

export interface UpdateEventSpot {
  /** @minLength 6 */
  name?: string;
  /**
   * Price in format `1000`
   * @minimum 0
   */
  price?: number;
  currency?: UpdateEventSpotCurrency;
}

export type CreateRolePermissionsItem = (typeof CreateRolePermissionsItem)[keyof typeof CreateRolePermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRolePermissionsItem = {
  eventcreate: "event.create",
  eventupdate: "event.update",
  eventduplicate: "event.duplicate",
  eventmanageApplications: "event.manageApplications",
  eventreviewSugarCubes: "event.reviewSugarCubes",
  organisationcreate: "organisation.create",
  organisationupdate: "organisation.update",
  organisationaddUser: "organisation.addUser",
  organisationupdateUser: "organisation.updateUser",
  organisationdeleteUser: "organisation.deleteUser",
  rolecreate: "role.create",
  roleupdate: "role.update",
  roledelete: "role.delete",
  userupdateRole: "user.updateRole",
  userdelete: "user.delete",
} as const;

export interface CreateRole {
  name: string;
  permissions?: CreateRolePermissionsItem[];
}

export interface Settings {
  id: string;
  termsAndConditions?: string;
  privacyPolicy?: string;
  footerDescription?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SettingsDTO {
  /** @nullable */
  termsAndConditions: string | null;
  /** @nullable */
  privacyPolicy: string | null;
  /** @nullable */
  footerDescription: string | null;
}

export interface CreateSugarCubeDto {
  /** Recipient user ID */
  toUserId: string;
  /** Sugar cube message */
  message: string;
  /** Whether the sender should be anonymous */
  isAnonymous: boolean;
}

/**
 * @nullable
 */
export type SugarCubeFromUser = EventApplication | null;

export interface SugarCube {
  id: number;
  /** Message */
  message: string;
  /** Whether the sender is anonymous */
  isAnonymous: boolean;
  /** Whether the sugar cube has been reported */
  isReported: boolean;
  /** @nullable */
  fromUser: SugarCubeFromUser;
  toUser: EventApplication;
  event: Event;
  createdAt: string;
}

export type SugarCubeRecipientOptionDtoGrouped = { [key: string]: User[] };

export interface SugarCubeRecipientOptionDto {
  grouped: SugarCubeRecipientOptionDtoGrouped;
}

export interface MailAddress {
  name: string;
  address: string;
}

export interface MailAttachment {
  filename: string;
  path: string;
}

export type SendEmailDTOPlaceholderReplacement = { [key: string]: unknown };

export interface SendEmailDTO {
  recipients: MailAddress[];
  subject: string;
  text?: string;
  html?: string;
  attachments?: MailAttachment[];
  placeholderReplacement?: SendEmailDTOPlaceholderReplacement;
}

export interface Error {
  [key: string]: unknown;
}

export type ForgotPasswordParams = {
  email: string;
};

export type VerifyEmailParams = {
  token: string;
};

export type ResendVerificationParams = {
  email: string;
};

export type GetAllUsersParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type GetAllUsers200 = {
  data?: User[];
  pagination?: PaginationDto;
};

export type GenerateSheetUsers200 = { [key: string]: unknown };

export type CreateOrganization201 = { [key: string]: unknown };

export type UpdateOrganization201 = { [key: string]: unknown };

export type TransferManager201 = { [key: string]: unknown };

export type OrganizationMembersParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type OrganizationMembers200 = {
  data?: OrganizationMember[];
  pagination?: PaginationDto;
};

export type GetUserApplicationsParams = {
  sinceSince?: number;
  toSince?: number;
};

export type GetUserApplications200 = {
  data?: EventApplication[];
  pagination?: PaginationDto;
};

export type GenerateSheetEventApplication200 = { [key: string]: unknown };

export type GetOngoingEventsParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type GetOngoingEvents200 = {
  data?: Event[];
  pagination?: PaginationDto;
};

export type GetEventsParams = {
  sinceSince?: number;
  toSince?: number;
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type GetEvents200 = {
  data?: Event[];
  pagination?: PaginationDto;
};

export type GetRoleAllPermissions200Item =
  (typeof GetRoleAllPermissions200Item)[keyof typeof GetRoleAllPermissions200Item];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoleAllPermissions200Item = {
  eventcreate: "event.create",
  eventupdate: "event.update",
  eventduplicate: "event.duplicate",
  eventmanageApplications: "event.manageApplications",
  eventreviewSugarCubes: "event.reviewSugarCubes",
  organisationcreate: "organisation.create",
  organisationupdate: "organisation.update",
  organisationaddUser: "organisation.addUser",
  organisationupdateUser: "organisation.updateUser",
  organisationdeleteUser: "organisation.deleteUser",
  rolecreate: "role.create",
  roleupdate: "role.update",
  roledelete: "role.delete",
  userupdateRole: "user.updateRole",
  userdelete: "user.delete",
} as const;

export type GetManagementEventsParams = {
  sinceSince?: number;
  toSince?: number;
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of results per page
   */
  perPage?: number;
  /**
   * If true, fetches all data (ignores pagination)
   */
  all?: boolean;
};

export type GetManagementEvents200 = {
  data?: Event[];
  pagination?: PaginationDto;
};
